### ISSUE TITLE
install

### ISSUE THREAD

**Issue by isanat** [nikandr-surkov/Hamster-Kombat-Telegram-Mini-App-Clone#1]
Can you help me install and test?

**Comment by avpersistence** [comment]
easy. What is your stage?

**Comment by RATcraftGames** [comment]
@avpersistence pls help me

**Comment by avpersistence** [comment]
> @avpersistence pls help me

Please let me know what is your stage or specify your question. Which problem you meet?

**Comment by otabekrizayev** [comment]
where is the error? I can't fix it. Please help me
I put await inside an async function. But another problem arises

file:///home/virtualman/Hamster-Kombat-Telegram-Mini-App-Clone/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
