### ISSUE TITLE
Project doesnt working

### ISSUE THREAD

**Issue by otabekrizayev** [nikandr-surkov/Hamster-Kombat-Telegram-Mini-App-Clone#13]
where is the error? I can't fix it. Please help me
I put await inside an async function. But another problem arises

file:///home/virtualman/Hamster-Kombat-Telegram-Mini-App-Clone/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
![photo_2024-10-18_12-50-26](https://github.com/user-attachments/assets/894269df-4737-4c7f-9da8-06269fe5a9ee)

**Comment by SoraKohaku** [comment]
try using nvm maybe this old  version npm.
